### ISSUE TITLE
dynamic theme from wallpaper applies after some delay

### ISSUE THREAD

**Issue by krupal4** [immutable-krupal/StatusSaver#3]
dynamic theme from mobile wallpaper applies after some delay for that delay we can show splash screen to improve user experience.

- Actual

> While dynamic theme is loading green color is getting applied

> `ColorScheme scheme = lightColorScheme ?? ColorScheme.fromSeed(seedColor: const Color(0x00FF00));`  

- Expected

> User should see splash screen untill dynamic theme request completes.

**Comment by Rishabh11200** [comment]
I'm not able to complete this PR near time soon... Can you do the required changes? Only the splash screen has to be turned off in the future of the main function (feature/dynamic theming) branch. Sorry for the inconvenience.

**Comment by krupal4** [comment]
Alright,
I have added fix for this issue.

**Comment by Rishabh11200** [comment]
> Alright, I have added fix for this issue.

Thanks 😁, great work!!!
