### ISSUE TITLE
Restrict App Permissions to Specific Folder Access Only (Avoid High-Risk User Permissions)

### ISSUE THREAD

**Issue by krupal4** [immutable-krupal/StatusSaver#6]
Currently, our app has high-risk user permissions that grant access to all files, which poses a potential security risk. We should modify the app's permissions to restrict access only to the specific folder ".Statuses" instead. This will help improve the security of the app and ensure that user data remains protected.

Please implement the necessary changes to limit the app's permissions and ensure that it only accesses the ".Statuses" folder.

> Make use of the more privacy-friendly [best practices](https://developer.android.com/training/data-storage#scoped-storage), such as the [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider) or the [MediaStore API](https://developer.android.com/training/data-storage/shared/media)

**Comment by ramponkiya** [comment]
@immutable-krupal  it's done or not permission for only accesses the ".Statuses" folder.

**Comment by krupal4** [comment]
@ramponkiya I have written code which uses SAF for .Statuses folder permission, will be pushing commit this week.
this change forced me to change many files, in the beginning, I was unaware of this permission that's why we are here :(.

**Comment by krupal4** [comment]
closing this issue since it is fixed in #20
